service: serverless-example
frameworkVersion: '>=3.0.0 <4.0.0'

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    usePipenv: false
    
package:
  patterns:
    - '!node_modules/**'
    - '!.venv/**'
    - '!Pipfile'
    - '!Pipfile.lock'
    - '!.python-version'
    - '!package.json'
    - '!package.-lock.json'
    - '!.nvmrc'

provider:
  name: aws
  stage: dev
  runtime: python3.10
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ec2:DescribeInstances
      Resource: "*"
  environment:
    POSTGRES_HOST: dummy
    POSTGRES_USER: dummy
    POSTGRES_PASSWORD: dummy
    POSTGRES_DATABASE: dummy

functions:
  saveToRDB:
    handler: src/handler.save_to_rdb
    events:
      - http:
          path: save
          method: post
