"""Create comment table

Revision ID: 9e68d6d33c99
Revises: f0d96aad08e5
Create Date: 2023-11-26 17:53:53.978423+09:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9e68d6d33c99'
down_revision = 'f0d96aad08e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('retrospective_method_id', sa.INTEGER(), nullable=False),
        sa.Column('user_id', sa.INTEGER(), nullable=False),
        sa.Column('comment', sa.VARCHAR(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id', name='comments_pkey'),
    )

    op.create_foreign_key(
        constraint_name="fk_user_id",
        source_table="comments",
        referent_table="users",
        local_cols=["user_id"],
        remote_cols=["id"],
        ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    # ### end Alembic commands ###
